### ISSUE TITLE
Set up a triplestore on the PhysMet Portal

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/tripper#315]

**Comment by jesper-friis** [comment]
Done. Available with the following configurations

```
PhysMet:
  backend: sparqlwrapper
  base_iri: https://physmetfuseki.azurewebsites.net/test-tem
  update_iri: https://physmetfuseki.azurewebsites.net/test-tem/update
  username: admin
  password: admin0
```
