### ISSUE TITLE
Using | in yaml description of datasets fails in graphdb backend, do we want that to work?

### ISSUE THREAD

**Issue by francescalb** [EMMC-ASBL/tripper#329]
This works:

```yaml
datasets:
- "@id": https://something.eu/dfsløjsdgfa
  "@type": http://emmc.eu/onto/Concept
  title: Concept title
  description: "This works"
  creator: me
  contactPoint: unknownemail
```

This does not work
```yaml
datasets:
- "@id": https://something.eu/dfsløjsdgfa
  "@type": http://emmc.eu/onto/Concept
  title: Concept title
  description: |
    This does not work
  creator: me
  contactPoint: unknownemail
```
